version: '3.8'

services:
  web:
    build: .
    image: like-machine
    env_file:
      - .docker_env/web.env
    ports:
      - 8000:8000
    volumes:
      - .:/code
    command: gunicorn like_machine_project.wsgi -b 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - .docker_env/db.env
    volumes:
      - like_machine_postgres_data:/var/lib/postgresql/data

volumes:
  like_machine_postgres_data:
    external: true
