# Generated by Django 3.2.3 on 2021-05-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_linkpost_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpost',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
